// Creative AI Tools Knowledge Graph Data
// Extracted from DreamLab Newsletter Issues 1-20 (240 tools)

export const CATEGORY_COLORS = {
  'Video':    '#3b82f6',
  'Image':    '#a855f7',
  '3D & VFX': '#10b981',
  'Audio':    '#f59e0b',
  'Agents':   '#eab308',
  'Coding':   '#06b6d4',
  'LLMs':     '#ef4444',
  'Games':    '#ec4899',
  'Design':   '#14b8a6',
  'Research': '#6b7280',
}

// [category, label, url, issues, tags, description]
const RAW = [
  // ─── Video Generation & Editing ────────────────────────────────────────────
  ['Video', 'Ingredients to Video', 'https://blog.google/innovation-and-ai/technology/ai/veo-3-1-ingredients-to-video/', '14', 'google,veo',
    "Generate videos directly inside YouTube Shorts and the YouTube Create app using Veo's Ingredients to Video feature."],
  ['Video', 'Google Flow (1B videos)', 'https://x.com/FlowbyGoogle/status/2016296853239955794', '16', 'google,flow',
    "1 billion videos have been generated in Google Flow, Google's AI video creation platform."],
  ['Video', 'Google Flow Refine', 'https://blog.google/technology/google-labs/flow-refine-videos/', '12', 'google,flow',
    "4 ways to refine content in Google Flow including prompt-by-doodling, adding/removing objects, and camera movement adjustment."],
  ['Video', 'ACE Studio Video2Music', 'https://www.youtube.com/watch?v=LxEtITCn96Q', '7', 'ace',
    "ACE Studio's Video to Music generates an original, royalty-free soundtrack that automatically syncs with your visuals."],
  ['Video', 'AI Compositing (ComfyUI)', 'https://github.com/rik-python/QWEN-AI-Compositing', '7', 'comfyui,qwen',
    "ComfyUI workflow for AI compositing — integrating subjects into scenes with realistic lighting and shadows using Qwen."],
  ['Video', 'AI Video in After Effects', 'https://www.linkedin.com/posts/thisisdoug_ai-aivideo-animation-ugcPost-7399512745924067330-Aldk', '9', 'adobe,aftereffects',
    "AI video generation is now animatable directly inside After Effects, bringing AI motion into professional VFX pipelines."],
  ['Video', 'Wan 2.2 Faceless Stream', 'https://x.com/eyishazyer/status/1983507594942755221', '5', 'wan',
    "Ali's Wan 2.2 workflow lets you stream content without showing your face using AI-generated video avatars."],
  ['Video', 'Animate Stills (Premiere)', 'https://www.youtube.com/watch?v=6vouJ9OB7RA', '7', 'adobe,premiere',
    "Free plugin for animating still images with AI inside Premiere Pro, After Effects, and Final Cut Pro using FX Factory Deep Pan."],
  ['Video', 'World Labs API', 'https://x.com/theworldlabs/status/2014046372639408203', '15', 'worldlabs',
    "API for generating persistent, explorable 3D worlds from text, images, and video."],
  ['Video', 'Avatar Forcing', 'https://taekyungki.github.io/AvatarForcing/', '13', 'avatar',
    "Real-time interactive head avatar generation for natural conversation that responds dynamically to user input."],
  ['Video', 'Sora Character Cameos', 'https://x.com/OpenAI/status/1983661036533379486', '5', 'sora,openai',
    "Character cameos are now available in the Sora app, enabling consistent characters across multiple video generations."],
  ['Video', 'Ovi 1.1 (CharacterAI)', 'https://github.com/character-ai/Ovi', '7', 'characterai,opensource',
    "CharacterAI's open-source Ovi 1.1 produces 10-second temporally consistent videos with synchronized speech and sound."],
  ['Video', 'BlendPack Transitions', 'https://github.com/SKBv0/ComfyUI_BlendPack', '15', 'comfyui',
    "Com-BlendPack: ComfyUI nodes for creating smooth video transitions between clips."],
  ['Video', 'ComfyUI SAM3 Video', 'https://x.com/wildmindai/status/1991482036557947290', '9', 'comfyui,meta,sam',
    "Meta's Segment Anything Model 3 integrated in ComfyUI for zero-shot object segmentation via text prompts."],
  ['Video', 'ComfyUI Veo 3 Workflow', 'https://github.com/lovisdotio/ComfyUI-Workflow-Sora2Alike-Full-loop-video', '4,10', 'comfyui,google,veo',
    "ComfyUI workflow that generates 2+ minute videos automatically by orchestrating Google Veo 3 and Imagen 3 APIs."],
  ['Video', 'AI Avatar (Unreal)', 'https://www.linkedin.com/posts/copresence-tech_want-to-create-an-intelligent-avatar-that-activity-7379523290421383168-SAg_', '4', 'unreal,avatar',
    "Tutorial for creating an intelligent AI avatar inside Unreal Engine that can converse and respond in real time."],
  ['Video', 'Veo Ref-to-Video', 'https://discuss.google.dev/t/a-spooky-day-in-the-life-veo-reference-images-nano-banana-and-the-art-of-canine-costumes/281607', '6', 'google,veo,nanobanana',
    "Create consistent characters using Veo's Reference-to-Video feature combined with Gemini 2.5 Flash."],
  ['Video', 'Decart LSD v2', 'https://www.reddit.com/r/Decart/comments/1ox7xe5/introducing_lsd_v2_our_new_flagship_realtime/', '8', 'decart,realtime',
    "Decart's LSD v2 is a realtime video-to-video model that you can prompt on the fly for live visual transformations."],
  ['Video', 'Wan ATI Trajectories', 'https://www.youtube.com/watch?v=AI9-1G7niXY', '6', 'wan',
    "Dive into the Wan ATI model for controlling video generation trajectories — dictate the path objects follow."],
  ['Video', 'DM Podcast #18', 'https://open.spotify.com/episode/3AlCPd4vA9QYA1HIqBgiHx', '18', 'podcast',
    "Dream Machine podcast episode 18 covering AI Piano Teachers, Chief AI Officers in Film, and AI Fatigue."],
  ['Video', 'DM Podcast #20', 'https://open.spotify.com/episode/79zQA8RuGJcSeGdOGASOOQ', '20', 'podcast',
    "Dream Machine podcast episode 20 covering Creative AI Jobs Boom, China's AI Film Studios, and Google 'Living Games'."],
  ['Video', 'DM Podcast Show', 'https://open.spotify.com/show/2ptbLwVWeyO7ooPGHoYTqk', '19', 'podcast',
    "DreamLab's podcast series: Explorations in Creative AI from the DreamLab Team, an Innovation Studio and Community."],
  ['Video', 'LiveAvatar Generation', 'https://liveavatar.github.io/', '11', 'avatar',
    "Audio-driven avatar generation with infinite length — create talking head videos from audio alone."],
  ['Video', 'ElevenLabs Image+Video', 'https://www.linkedin.com/posts/elevenlabsio_introducing-elevenlabs-image-video-the-activity-7396231143492251649-KSLy', '8', 'elevenlabs',
    "ElevenLabs launches Image and Video Beta, expanding from audio into visual content generation."],
  ['Video', 'Weavy Video Transform', 'https://www.youtube.com/watch?v=K-AVMMLJbpQ', '7', 'weavy',
    "Weavy Video Transformation brings everything you can do to images — edits, compositing, effects — now to video."],
  ['Video', 'Veo 3.1 Full Tutorial', 'https://www.youtube.com/watch?v=Z5DLMAi18eE', '4', 'google,veo',
    "Full Veo 3.1 tutorial covering consistent characters, extended scenes, and advanced generation techniques."],
  ['Video', 'LTX-2 Audio+Video', 'https://x.com/ltx_model/status/1985331659474907221', '6', 'ltx',
    "Generate 20-second continuous, synchronized audio and video natively with LTX-2."],
  ['Video', 'Invideo AI + Gemini', 'https://x.com/googlecloud/status/1987522314875842856', '7', 'google,gemini',
    "Generate a full-fledged video ad by writing a single prompt with the Invideo AI Agent, built on Gemini."],
  ['Video', 'Google Video Avatars', 'https://vids.new/', '12', 'google,avatar',
    "Google Video Avatars got a big upgrade in expressiveness — more natural, emotive AI presenter avatars."],
  ['Video', 'Hedra Elements', 'https://x.com/hedra_labs/status/2013674528938041691', '15', 'hedra',
    "Hedra Elements lets you build scenes by combining reusable components — a modular approach to AI video creation."],
  ['Video', 'Hedra Audio Tags', 'https://x.com/hedra_labs/status/1998490844748460528', '11', 'hedra',
    "Hedra's Audio Tags let you tag any audio with precise emotions for fully controllable, more natural-sounding avatar expression."],
  ['Video', 'HeyGen + VEO 3.1', 'https://x.com/HeyGen_Official/status/1978491090618749193', '4', 'heygen,google,veo',
    "HeyGen is bringing identity consistency to Veo 3.1 — maintain a specific person's likeness across generated videos."],
  ['Video', 'HeyGen Motion Designer', 'https://www.linkedin.com/posts/heygen_if-you-can-explain-it-you-can-animate-it-activity-7387488068204892160-AY8-', '5', 'heygen',
    "HeyGen Motion Designer elevates your video by creating motion graphics from just a text prompt."],
  ['Video', 'Higgsfield Relight', 'https://higgsfield.ai/app/relight', '13', 'higgsfield',
    "Higgsfield AI's Relight feature lets you change the lighting of any scene in an existing video."],
  ['Video', 'Higgsfield Sketch2Video', 'https://higgsfield.ai/posts/6nkYSGwOcdyXVqZefE1MsQ', '3', 'higgsfield,sora',
    "Higgsfield drops Sketch to Video powered by Sora 2 — draw a rough sketch and animate it into video."],
  ['Video', 'Higgsfield Popcorn', 'https://x.com/higgsfield_ai/status/1981110992630341928', '4', 'higgsfield',
    "Higgsfield Popcorn is an AI storyboard tool with character consistency across multiple shots."],
  ['Video', 'Higgsfield Shots', 'https://higgsfield.ai/app/shots', '12', 'higgsfield',
    "Higgsfield Shots generates multiple storyboard images from a single reference shot for rapid pre-visualization."],
  ['Video', 'Higgsfield WAN Camera', 'https://www.linkedin.com/posts/meet-higgsfield-wan-camera-control-cinematic-ugcPost-7391427693021470721-kQ7_', '6', 'higgsfield,wan',
    "Higgsfield WAN Camera Control brings cinematic camera movement control to Wan-based video generation."],
  ['Video', 'Premiere Object Mask', 'https://www.linkedin.com/posts/robdewinter_ok-this-is-going-to-save-a-lot-of-time-in-ugcPost-7421617551690063872-yKmB', '16', 'adobe,premiere',
    "The new Object Mask tool in Adobe Premiere Pro uses AI to automatically mask and track objects in footage."],
  ['Video', 'LTX-2 LoRA Training', 'https://www.youtube.com/watch?v=po2SpJtPdLs', '15', 'ltx,lora',
    "Tutorial on how to train a character LoRA for LTX-2 using the AI Toolkit for consistent characters."],
  ['Video', 'Flow Consistency Tips', 'https://x.com/FlowbyGoogle/status/2013783718415282596', '15', 'google,flow',
    "Filmmaker Niklas Klabunde shares helpful consistency tips for working with Veo and Google Flow."],
  ['Video', 'Runway Gen-4.5 I2V', 'https://www.youtube.com/watch?v=AwKSrJFvdps', '15', 'runway',
    "Runway introduces Gen-4.5 Image to Video, a state-of-the-art model for animating still images."],
  ['Video', 'Runway Gen-4.5', 'https://www.youtube.com/watch?v=ei2PsDpPbB4', '10', 'runway',
    "Runway releases Gen 4.5, a state-of-the-art video generation model with improved quality and control."],
  ['Video', 'LTX-2 Launch', 'https://x.com/ltx_model/status/1981346235194683497', '5', 'ltx,opensource',
    "Introducing LTX-2: the most complete open-source AI creative engine for video generation with audio support."],
  ['Video', 'Keyframe (After Effects)', 'https://ericday.gumroad.com/l/keyframe', '2', 'adobe,aftereffects',
    "Keyframe brings the power of Replicate's best AI models directly into After Effects for motion work."],
  ['Video', 'LTX-2 Audio (ComfyUI)', 'https://github.com/purzbeats/purz-comfyui-workflows/blob/main/ltx2/ltx2-audio_to_video_extension_5x.json', '15', 'ltx,comfyui',
    "KJNodes update enabling audio as input for LTX-2 video generation inside ComfyUI."],
  ['Video', 'Kling O1 Tutorial', 'https://www.youtube.com/watch?v=BuesDSXFffM', '10', 'kling',
    "Tutorial on using Kling O1 to modify and edit existing AI-generated videos with precise control."],
  ['Video', 'Kling VIDEO 01', 'https://app.klingai.com/global/release-notes/vaxrndo66h', '10', 'kling',
    "Kling releases the VIDEO 01 Model, a new flagship video generation model with improved consistency."],
  ['Video', 'LiveAvatar (HeyGen)', 'https://www.liveavatar.com/', '7', 'heygen,avatar',
    "HeyGen's LiveAvatar offers hyper-realistic, real-time interactive avatars that enable human presence on demand at scale."],
  ['Video', 'LiveGS Gaussian Splat', 'https://discovery.researcher.life/article/livegs-live-free-viewpoint-video-via-high-performance-gaussian-splatting-for-mobile-devices/5e862bea09243669b6a75e724a3318e6', '3', 'gaussian',
    "LiveGS: Live free-viewpoint video via high-performance Gaussian Splatting optimised for mobile devices."],
  ['Video', 'LTX-2 Audio API', 'https://x.com/ltx_model/status/2016166995193167948', '16', 'ltx',
    "LTX-2 Audio-to-Video is now available via API, enabling programmatic access to synchronized audio-video generation."],
  ['Video', 'LTX-2 in ComfyUI', 'https://blog.comfy.org/p/ltx-2-open-source-audio-video-ai', '13', 'ltx,comfyui',
    "LTX-2 is natively supported in ComfyUI, bringing open-source audio-video AI generation into the workflow."],
  ['Video', 'LTX-2 Dialogue', 'https://x.com/ltx_model/status/2011101440706806051', '14', 'ltx',
    "LTX-2 produces audio and lip-synced dialogue natively with leading open-source quality."],
  ['Video', 'LTX-2 Trainer (fal)', 'https://fal.ai/models/fal-ai/ltx2-video-trainer', '14', 'ltx',
    "LTX-2 Trainer is now on fal.ai, enabling you to create custom character LoRAs for LTX-2 video generation."],
  ['Video', 'Olympics Ad (Mathematic)', 'https://www.linkedin.com/posts/mathematic-studio_olympic-paralympic-games-making-of-activity-7391099196755427328-CZfH/', '6', 'production',
    "Mathematic, a French creative studio, made the 2026 Olympics ad using a traditional 3D pipeline augmented with AI."],
  ['Video', 'MIMIX Character Mix', 'https://tingtingliao.github.io/mimix/', '2', 'character',
    "MIMIX enables character mixing for video generation — blend attributes from multiple reference characters."],
  ['Video', 'MocapAnything (Huawei)', 'https://www.linkedin.com/posts/petewoodbridge_ai-creativeai-mocap-activity-7405511766698364929-fzM8', '12', 'huawei,mocap',
    "MocapAnything from Huawei: unified 3D motion capture for arbitrary skeletons from monocular video input."],
  ['Video', 'MotionStream Realtime', 'https://x.com/wildmindai/status/1985828041566941576', '6', 'realtime',
    "MotionStream: real-time interactive video generation with mouse-based motion control, running at 29 FPS with 0.4s latency."],
  ['Video', 'Kling 2.6 Motion Ctrl', 'https://x.com/Kling_ai/status/2001306445262823431', '12', 'kling',
    "Kling 2.6 upgrades Motion Control to support reference videos up to 30 seconds with complex movement. Includes new APIs."],
  ['Video', 'Next Scene (HF)', 'https://huggingface.co/lovis93/next-scene-qwen-image-lora-2509', '2', 'huggingface,qwen',
    "Next Scene generates cinematic image sequences with natural visual progression from frame to frame."],
  ['Video', 'NVIDIA ChronoEdit', 'https://www.reddit.com/r/aicuriosity/comments/1o1coo3/chronoedit_nvidias_ai_tool_revolutionizes_image/', '5', 'nvidia',
    "NVIDIA ChronoEdit on Hugging Face brings temporal reasoning to image editing, enabling physics-aware changes and world simulation."],
  ['Video', 'NVIDIA Omniverse Fixer', 'https://www.linkedin.com/posts/looking-to-enhance-3d-gaussian-reconstruction-share-7402063987041116160-cFQ1', '10', 'nvidia,gaussian',
    "NVIDIA Omniverse Fixer is a diffusion-based model that removes rendering artifacts in Gaussians and restores detail in lower quality regions."],
  ['Video', 'Odyssey 2', 'https://odyssey.ml/introducing-odyssey-2', '5', 'odyssey,realtime',
    "Odyssey 2 is an entirely new way to interact with real-time AI video — an interactive world model."],
  ['Video', 'Odyssey 2 (16:9)', 'https://x.com/olivercameron/status/1984777003967672800', '6', 'odyssey,realtime',
    "Odyssey 2 interactive video model now streams full 16:9 video in real time."],
  ['Video', 'Open Vision Agents', 'https://github.com/GetStream/Vision-Agents', '11', 'agents,opensource',
    "Open Vision Agents: a toolkit for building agents that watch, listen, and understand video streams."],
  ['Video', 'Qwen Multi-Angle LoRA', 'https://x.com/multimodalart/status/1986174924038218087', '6', 'qwen,lora',
    "Qwen Image Multiple Angles LoRA keeps characters and scenes consistent across different camera viewpoints."],
  ['Video', 'Runway Workflows', 'https://www.linkedin.com/posts/runwayml_introducing-workflows-a-new-way-to-build-ugcPost-7386500481382244352-qeC8', '4', 'runway',
    "Runway introduces Workflows: use nodes to chain multiple models, modalities, and intermediary steps for fine-grained generation control."],
  ['Video', 'Runway Gen-4.5 I2V All', 'https://www.linkedin.com/posts/runwayml_introducing-image-to-video-for-gen-45-the-activity-7419856988186238976-ZJU2', '15', 'runway',
    "Runway Gen-4.5 Image to Video is now available for all paid plans."],
  ['Video', 'Runway Story Panels', 'https://www.linkedin.com/posts/runwayml_introducing-the-story-panels-app-a-simple-activity-7416859523858034688-SdwW', '14', 'runway',
    "Runway's Story Panels app turns a single character or product image into a three-panel narrative stack."],
  ['Video', 'Runway Audio Nodes', 'https://www.linkedin.com/posts/introducing-audio-nodes-for-runway-workflows-share-7397314648074735616-XRZX', '9', 'runway',
    "Runway introduces Audio Nodes for Runway Workflows, enabling audio manipulation within the node-based pipeline."],
  ['Video', 'Runway Fine Tuning', 'https://runwayml.com/product/model-fine-tuning', '4', 'runway',
    "Runway introduces Model Fine Tuning to help unlock new use cases with custom-trained video generation models."],
  ['Video', 'Runway Gen 4.5 Launch', 'https://runwayml.com/research/introducing-runway-gen-4.5', '10', 'runway',
    "Runway releases Gen 4.5, a state-of-the-art video generation model with enhanced realism and control."],
  ['Video', 'Runway VFX Apps', 'https://x.com/runwayml/status/1978540984595026320', '3', 'runway',
    "Runway releases new VFX apps with customised workflows for changing weather, background, time of day, and scene relighting."],
  ['Video', 'Runway Remove Video', 'https://www.linkedin.com/posts/priyanka-rana-77003b1b_aifeature-aitools-runwayml-ugcPost-7387073935860871169-ya5R', '6', 'runway',
    "Runway Remove from Video: upload a video, describe the element you want removed, and it disappears."],
  ['Video', 'Premiere Semantic Audio', 'https://www.linkedin.com/posts/justinsalamon_search-for-any-sound-in-your-video-footage-ugcPost-7397053251243732992-ve76/', '8', 'adobe,premiere',
    "Semantic Audio Search is now live in Premiere Pro — search for any sound in video footage using natural language."],
  ['Video', 'Veo 3.1 Tips (Google)', 'https://x.com/GoogleDeepMind/status/1980261047836508213', '4', 'google,veo',
    "Google's helpful tips for using Veo 3.1, plus new precision capabilities to remove or add elements to a scene."],
  ['Video', 'Sora 2 ComfyUI Nodes', 'https://blog.comfy.org/p/sora-2-api-nodes-now-in-comfyui', '2', 'comfyui,sora',
    "Sora 2 API nodes are now integrated in ComfyUI, bringing OpenAI's video generation into ComfyUI workflows."],
  ['Video', 'Sora 1M Downloads', 'https://www.linkedin.com/news/story/sora-tops-1m-downloads-in-5-days-6684988/', '3', 'sora,openai',
    "Sora tops 1 million downloads in just 5 days following its public launch."],
  ['Video', 'Stable Audio 2.5', 'https://stability.ai/learning-hub/stability-seconds-create-a-soundtrack-with-stable-audio-25', '3', 'stability',
    "Stability AI's Stable Audio 2.5 tutorial for generating custom, commercially safe audio for video projects."],
  ['Video', 'LTX-2 Tutorial (ComfyUI)', 'https://x.com/cocktailpeanut/status/2011217121808699482', '14', 'ltx,comfyui',
    "Super comprehensive tutorial on running LTX-2 with both WanGP and ComfyUI for audio-video generation."],
  ['Video', 'Tether (After Effects)', 'https://www.linkedin.com/posts/thisisdoug_aftereffects-aivideo-vfx-ugcPost-7368671859774517249-l0sz', '1', 'adobe,aftereffects',
    "Tether: directable AI animation all inside of Adobe After Effects — control AI-generated motion frame by frame."],
  ['Video', 'Wan 2.2 ComfyUI Tips', 'https://x.com/ComfyUI/status/1984379904176373983', '6', 'wan,comfyui',
    "Tips for control and quality when using Wan 2.2 Animate inside ComfyUI."],
  ['Video', 'Runway Create Ads', 'https://x.com/runwayml/status/1983519980839969077', '5', 'runway',
    "Runway Create Ads app turns any existing ad into endless new iterations — part of the Runway Apps for Advertising collection."],
  ['Video', 'Sora 2 + n8n Tutorial', 'https://www.youtube.com/watch?v=Vm8QOo9MiC4', '4', 'sora,n8n',
    "Tutorial on creating anything with Sora 2 combined with n8n automation agents."],
  ['Video', 'Runway Workflows Tut', 'https://www.youtube.com/watch?v=MsVl_CKu_gk', '7', 'runway',
    "Runway Academy tutorial on Using Workflows — how to build and execute node-based AI video pipelines."],
  ['Video', 'VEED Transitions', 'https://x.com/veedstudio/status/1980636419891818850', '4', 'veed',
    "VEED Transitions lets you create mindblowing video transitions in seconds using AI."],
  ['Video', 'Veo 3.1 Vertical+4K', 'https://x.com/FlowbyGoogle/status/2011130097483526474', '14', 'google,veo',
    "Veo 3.1 Ingredients to Video now supports vertical formats with a more expressive model and upscaling to 1080p and 4K."],
  ['Video', 'Veo 3.1 Preview', 'https://www.cometapi.com/veo-3-1-is-comingand-whats-rumor/', '2', 'google,veo',
    "Veo 3.1 is nearly here with improved consistency, resolution, multishot generation, cinematic presets, and longer generations."],
  ['Video', 'HeyGen Video Agent', 'https://www.linkedin.com/posts/heygen_introducing-the-new-video-agent-activity-7421597801240801282-d1CF', '16', 'heygen',
    "HeyGen Video Agent lets you script, edit, and create entire videos with reference images using a conversational AI agent."],
  ['Video', 'Video Stab (ComfyUI)', 'https://www.youtube.com/watch?v=Bbh9Bpi_Zlw', '19', 'comfyui',
    "Free ComfyUI workflow for AI-powered video stabilization."],
  ['Video', 'VideoSOS Editor', 'https://github.com/timoncool/videosos/', '5', 'opensource',
    "VideoSOS: an open-source AI-powered video editor for general video editing tasks."],
  ['Video', 'Vimeo AI Tools', 'https://www.tvtechnology.com/news/vimeo-releases-new-ai-powered-creator-tools', '5', 'vimeo',
    "Vimeo releases new AI-powered creator tools for video hosting and production workflows."],
  ['Video', 'Wan 2.6', 'https://wan.video/blog/wan2.6-introduction', '12', 'wan',
    "Wan 2.6 lets you cast characters from reference videos into new scenes. Up to 15 seconds with multishot capabilities."],
  ['Video', 'WorldLabs RTFM', 'https://www.worldlabs.ai/blog/rtfm', '4', 'worldlabs,realtime',
    "WorldLabs introduces RTFM (Real-Time Frame Model): a highly efficient World Model generating video frames in real time."],

  // ─── Image Generation & Editing ──────────────────────────────────────────────
  ['Image', '3D Loader + Anime2Real', 'https://www.linkedin.com/posts/ernest-marine_qwen-ai-animetoreal-ugcPost-7394694147686785024-V55Y', '8', 'comfyui,qwen,lora',
    "3D loader and Anime2Real LoRA for ComfyUI — convert anime-style images to photorealistic renders."],
  ['Image', 'Illustrator Turntable', 'https://x.com/DrFonts/status/1976322430705774785', '3', 'adobe',
    "Adobe Illustrator Turntable Tool for creating 360-degree rotational views of illustrated objects."],
  ['Image', 'Apply Texture LoRA', 'https://huggingface.co/tarn59/apply_texture_qwen_image_edit_2509', '8', 'qwen,lora,huggingface',
    "ComfyUI workflow to apply any texture to anything using a Qwen-based LoRA."],
  ['Image', 'Beeble Switchlight 3', 'https://beeble.ai/beeble-studio', '6', 'beeble,relighting',
    "Beeble Switchlight 3: AI-powered masking and re-lighting tool, bringing LED volume benefits to flexible chroma workflows."],
  ['Image', 'FLUX 2 Max', 'https://bfl.ai/models/flux-2-max', '12', 'bfl,flux',
    "Black Forest Labs releases FLUX 2 Max — their most capable image generation model."],
  ['Image', 'FLUX 2 Open Source', 'https://www.linkedin.com/posts/bflai_flux2-is-here-our-most-capable-image-generation-ugcPost-7399119735336116224-nRmt', '9', 'bfl,flux,opensource',
    "Black Forest Labs releases open-source FLUX 2 with improved speed, quality, precision control, and open weights."],
  ['Image', 'SeeDream 4.5', 'https://seed.bytedance.com/en/seedream4_5', '10', 'bytedance',
    "Bytedance releases SeeDream 4.5, their advanced image generation model."],
  ['Image', 'CanvAI Sketch to Art', 'https://www.canvai.co/', '11', 'canvai',
    "CanvAI turns rough sketches into polished AI art — draw anything and watch it transform."],
  ['Image', 'Qwen-Edit ReLight', 'https://x.com/wildmindai/status/1984918838463668616', '6', 'qwen,relighting,lora',
    "Qwen-Edit 2509 ReLight LoRA gives you total control over your image's atmosphere and lighting."],
  ['Image', 'Day to Night (ComfyUI)', 'https://huggingface.co/lividtm/Qwen-Edit-Loras', '9', 'comfyui,qwen,lora',
    "ComfyUI Day to Night conversion using the Qwen Edit LoRA for seamless time-of-day transformations."],
  ['Image', 'ComfyUI SAM3', 'https://github.com/PozzettiAndrea/ComfyUI-SAM3', '9', 'comfyui,meta,sam',
    "ComfyUI integration for Meta's SAM 3 (Segment Anything Model 3) for precise object segmentation."],
  ['Image', 'Qwen i2L LoRA', 'https://x.com/ModelScope2022/status/1998408862211441107', '11', 'qwen,lora',
    "DiffSynth-Studio drops Qwen-Image-i2L — the first open-source suite that turns a single image into a custom LoRA."],
  ['Image', 'Adobe Express + ChatGPT', 'https://blog.adobe.com/en/publish/2025/12/10/edit-photoshop-chatgpt', '12', 'adobe,openai',
    "Edit images, designs, and PDFs right inside OpenAI ChatGPT — thanks to Adobe Express, Photoshop, and Acrobat integration."],
  ['Image', 'FLUX 2 Multi-Angle', 'https://fal.ai/models/fal-ai/flux-2-lora-gallery/multiple-angles/playground', '10', 'bfl,flux,lora',
    "FLUX 2 Multiple Angle LoRA enables consistent character rendering from different viewpoints."],
  ['Image', 'Multi-Angle Relight LoRA', 'https://huggingface.co/dx8152/Qwen-Edit-2509-Multi-Angle-Lighting', '8', 'qwen,relighting,lora',
    "AI to AR workflow: Multi-Angle Relighting LoRA for consistent lighting across different viewing angles."],
  ['Image', 'BandLab Voice Cleaner', 'https://musictech.com/features/how-to-remove-background-noise-from-your-vocals-within-seconds-using-bandlabs-voice-cleaner/', '10', 'bandlab',
    "BandLab's Voice Cleaner removes background noise from vocals within seconds using AI."],
  ['Image', 'Meta SAM 3 Intro', 'https://www.youtube.com/watch?v=G4OLPDjwncw', '8', 'meta,sam',
    "Introduction to Meta's Segment Anything Model 3 (SAM 3) — unified segmentation, detection, and tracking."],
  ['Image', 'Krea Nodes', 'https://www.linkedin.com/posts/krea-ai_introducing-krea-nodes-our-most-powerful-ugcPost-7392114561518039040-q3Jc/', '6', 'krea',
    "Krea introduces Nodes — their most powerful feature yet, enabling complex image generation pipelines."],
  ['Image', 'Krea Realtime Edit', 'https://www.linkedin.com/posts/krea-ai_introducing-realtime-edit-now-like-with-activity-7420129381307592704-zUWY', '16', 'krea,realtime',
    "Krea introduces Realtime Edit — edit images with complex instructions in real time as you type."],
  ['Image', 'Krea Realtime OSS', 'https://www.linkedin.com/posts/krea-ai_today-were-open-sourcing-krea-realtime-activity-7386124532207689728-B7pD', '4', 'krea,opensource,realtime',
    "Krea Realtime has gone open source — the real-time AI image generation engine is now available to everyone."],
  ['Image', 'Loveart Layer Sep', 'https://x.com/lovart_ai/status/1987888703444865131', '7', 'loveart',
    "Loveart AI extracts and edits text, subjects, and backgrounds with Layer Separation and Live Editable Text (LET)."],
  ['Image', 'Magnific Precision v2', 'https://www.linkedin.com/posts/magnific-ai_introducing-magnific-precision-v2-activity-7387158930776276992-zpET', '5', 'magnific',
    "Magnific Precision v2: super natural, realistic image upscaling that looks just like the original photo."],
  ['Image', 'Meta SAM Audio', 'https://about.fb.com/news/2025/12/our-new-sam-audio-model-transforms-audio-editing/', '12', 'meta,sam',
    "Meta introduces the Segment Anything Audio Model (SAMAudio) — transforming audio editing with precise sound isolation."],
  ['Image', 'Meta SAM 3 + SAM 3D', 'https://www.linkedin.com/posts/aiatmeta_introducing-sam-3-sam-3d-ugcPost-7396944913751465985-m5Nc', '8', 'meta,sam',
    "Meta releases SAM 3 and SAM 3D — enabling detecting, segmenting, tracking objects and precise 3D reconstruction."],
  ['Image', 'Midjourney Style Creator', 'https://x.com/midjourney/status/1991684484455100477', '9', 'midjourney',
    "Midjourney releases an early version of their Style Creator — define and reuse custom visual styles."],
  ['Image', 'NanoBanana LoRA Gen', 'https://lovis.io/NanoBananaLoraDatasetGenerator/', '11', 'nanobanana,lora',
    "NanoBanana Pro LoRA Dataset Generator lets you create training datasets for image editing models in minutes."],
  ['Image', 'PercHead 3D Heads', 'https://antoniooroz.github.io/PercHead/', '6', '3dhead',
    "PercHead reconstructs realistic 3D heads from a single image with disentangled 3D editing via geometric controls."],
  ['Image', 'PractiLight', 'https://www.linkedin.com/posts/alexandremorgand_relighting-lightcontrol-diffusionmodels-ugcPost-7372207289639911424-zb-9', '3', 'relighting',
    "PractiLight: practical light control using foundational diffusion models — relight any image with precision."],
  ['Image', 'Qwen-Edit Multi-Angles', 'https://x.com/wildmindai/status/1984882709051679157', '6', 'qwen',
    "Qwen-Edit 2509 Multiple-angles LoRA enables camera movement commands: up, down, left, right, rotation, and focal changes."],
  ['Image', 'Qwen-Image-2512', 'https://qwen.ai/blog?id=qwen-image-2512', '13', 'qwen',
    "Qwen-Image-2512 is the latest version of the Qwen image editing model with improved instruction following."],
  ['Image', 'Qwen Gaussian 3D Cam', 'https://www.youtube.com/watch?v=9Vyxjty9Qao', '14', 'qwen,gaussian',
    "Qwen-Image-Edit 2511 Gaussian Splash 3D Camera Motion — generate 3D camera movements from still images."],
  ['Image', 'Qwen Multi-Angles (fal)', 'https://fal.ai/models/fal-ai/qwen-image-edit-2511-multiple-angles', '13', 'qwen',
    "Qwen-Image-Edit-2511-Multiple-Angles-LoRA now available on fal.ai for easy cloud-based access."],
  ['Image', 'Qwen Light Transfer', 'https://huggingface.co/dx8152/Qwen-Edit-2509-Light-Migration', '11', 'qwen,relighting,lora',
    "QwenEdit-2509 Light Transfer LoRA: simple and powerful image relighting using a reference image for lighting style."],
  ['Image', 'Qwen Anything2Real', 'https://huggingface.co/lrzjason/Anything2Real_2601', '13', 'qwen,lora',
    "QwenEdit-2511 Anything2Real LoRA converts any art style — anime, sketch, cartoon — to photorealistic images."],
  ['Image', 'Refocus Photo AI', 'https://www.youtube.com/watch?v=CMh_jGDl-RE', '13', 'photo',
    "Refocus any photo with AI — change the depth of field and focal point of existing photographs."],
  ['Image', 'Qwen AnyPose', 'https://huggingface.co/spaces/linoyts/Qwen-Image-Edit-2511-AnyPose', '13', 'qwen',
    "Transfer any pose from a reference image to your subject using the Qwen AnyPose model."],
  ['Image', 'SAM3 Demo', 'https://www.aidemos.meta.com/segment-anything/editor/convert-image-to-3d', '9', 'meta,sam',
    "Try out SAM3 — Meta's interactive demo for Segment Anything Model 3 including image-to-3D conversion."],
  ['Image', 'Krea LoRA Training', 'https://www.linkedin.com/posts/krea-ai_introducing-trainers-for-qwen-2512-and-z-image-activity-7415052197916299264-e-8K', '13', 'krea,qwen,lora',
    "Train LoRAs for Qwen-2512 and Z-Image directly in krea.ai for custom style and subject training."],

  // ─── 3D, VFX & Motion ────────────────────────────────────────────────────────
  ['3D & VFX', '3D + ComfyUI Workflow', 'https://www.linkedin.com/posts/st%C3%A9phane-davi-9082754a_vfx-3d-ai-ugcPost-7397126119193292800-iyMv', '8', 'comfyui',
    "A cool 3D and ComfyUI workflow from Imago Pictures combining 3D renders with AI image generation."],
  ['3D & VFX', 'Apple SHARP', 'https://huggingface.co/apple/Sharp', '12', 'apple',
    "Apple SHARP on Hugging Face: photorealistic 3D view synthesis from a single image in less than a second."],
  ['3D & VFX', 'Autodesk Flow Studio', 'https://www.linkedin.com/posts/autodesk-media-%26-entertainment_autodesk-flow-studio-creator-reel-activity-7381704369152499712-Vr6M', '3', 'autodesk,mocap',
    "AUTODESK Flow Studio delivers editable, AI-powered motion capture, camera tracking, and 3D animation."],
  ['3D & VFX', 'Depth Anything 3', 'https://huggingface.co/spaces/depth-anything/depth-anything-3', '8', 'bytedance,depth',
    "Bytedance Depth Anything 3 lets you recover the visual space from any view — monocular depth estimation at scale."],
  ['3D & VFX', 'Cascadeur AI Anim', 'https://www.linkedin.com/posts/cascadeur3d_new-cascadeur-update-20253-is-live-big-activity-7400224420994158592-kv5c', '10', 'cascadeur,animation',
    "Cascadeur's impressive AI Animation update adds to AI interpolation features that run locally on your PC."],
  ['3D & VFX', 'ComfyUI Depth Anything', 'https://github.com/PozzettiAndrea/ComfyUI-DepthAnythingV3', '8', 'comfyui,bytedance,depth',
    "ComfyUI custom node for Depth Anything V3 — extract depth maps from any image or video inside ComfyUI."],
  ['3D & VFX', 'Blender MCP + Claude', 'https://github.com/ahujasid/blender-mcp', '14', 'blender,anthropic',
    "Connect Claude to Blender with the Blender MCP — control 3D scenes and generate assets using natural language."],
  ['3D & VFX', 'Decart Lucy 2.0', 'https://x.com/DecartAI/status/2015937856351440971', '16', 'decart,realtime',
    "Decart introduces Lucy 2.0: a Realtime World Editing Model running at 1080p, 30 FPS."],
  ['3D & VFX', 'Depth Anything 3 Video', 'https://www.youtube.com/watch?v=bw2ErGkghlE', '8', 'bytedance,depth',
    "Depth Anything 3 by ByteDance — recovering the visual space from any view, demonstrated on video."],
  ['3D & VFX', 'Depth + ComfyUI+Blender', 'https://x.com/OlstFlow/status/1990397908315762791', '10', 'comfyui,blender,depth',
    "DepthAnything workflow using ComfyUI and Blender together for depth-based 3D scene reconstruction."],
  ['3D & VFX', 'ECHO (SpAItial)', 'https://www.spaitial.ai/', '12', 'spaitial',
    "ECHO is a new world model and spatial foundation model from SpAItial for understanding 3D environments."],
  ['3D & VFX', 'Gemini in Unreal', 'https://www.linkedin.com/posts/wouterweynants_gemini-nano-banana-x-unreal-engine-straight-ugcPost-7366849132893839361-GjWu', '1', 'google,gemini,unreal,nanobanana',
    "Gemini's Nano Banana inside Unreal Engine — AI-driven real-time content generation within UE5."],
  ['3D & VFX', 'NVIDIA Audio2Face Tut', 'https://www.youtube.com/watch?v=-l8kjQUTfQk', '8', 'nvidia,audio2face',
    "Getting started with NVIDIA Audio2Face-3D Open Source — drive facial animation from audio in real time."],
  ['3D & VFX', 'Grok Imagine + 3D Tools', 'https://www.youtube.com/watch?v=Z6oZf7k5oy0', '17', 'comfyui,xai',
    "Grok Imagine API in ComfyUI with a set of 3D tools to track and edit camera trajectories."],
  ['3D & VFX', 'Hitem3D', 'https://www.hitem3d.ai/', '5', 'hitem3d',
    "Hitem3D: AI-powered next-gen high resolution 3D model generator from text or image input."],
  ['3D & VFX', 'Gaussian Splat Anims', 'https://80.lv/articles/how-to-create-simple-animations-using-3d-gaussian-splats', '7', 'gaussian',
    "How to create simple animations of yourself using 3D Gaussian Splats."],
  ['3D & VFX', 'Hunyuan 3D Studio', 'https://x.com/TencentHunyuan/status/1994254918258184329', '9', 'tencent,hunyuan',
    "Hunyuan 3D Studio now integrates Hunyuan 3D-PolyGen 1.5, an art-grade 3D generative model from Tencent."],
  ['3D & VFX', 'Hyper3D', 'https://hyper3d.ai/', '10', 'hyper3d',
    "Hyper3D for Designers: create high-precision 3D models from text or images using Hyper3D's advanced AI engine."],
  ['3D & VFX', 'Meshy 6 (ComfyUI)', 'https://x.com/MeshyAI/status/2013642683361681849', '15', 'meshy,comfyui',
    "Meshy 6 is now natively available in ComfyUI for seamless 3D model generation within workflows."],
  ['3D & VFX', 'Meshy Any Pose', 'https://x.com/MeshyAI/status/2013917607162720503', '15', 'meshy',
    "Meshy Image to 3D now works in ANY pose — generate 3D models from images regardless of the subject's orientation."],
  ['3D & VFX', 'Meta Hyperscape', 'https://www.meta.com/en-gb/experiences/meta-horizon-hyperscape-capture-beta/8798130056953686/', '1', 'meta,gaussian',
    "Meta's Gaussian Splatting platform Hyperscape — capture splats using your Quest headset."],
  ['3D & VFX', 'Trellis 2 (Microsoft)', 'https://github.com/microsoft/TRELLIS.2', '12', 'microsoft',
    "Microsoft Trellis 2: Native and Compact Structured Latents for 3D Generation with improved quality and speed."],
  ['3D & VFX', 'Nano Banana x Nuke', 'https://www.linkedin.com/posts/activity-7404587066442928129-YPYL', '11', 'nanobanana,nuke',
    "Nano Banana x Nuke — a Nuke node that connects Nano Banana directly through the FAL AI API for VFX pipelines."],
  ['3D & VFX', 'NVIDIA Audio2Face OSS', 'https://www.pcgamer.com/hardware/graphics-cards/nvidias-gen-ai-facial-animation-tech-is-going-open-source-potentially-making-it-much-easier-for-game-devs-to-turn-real-time-speech-into-convincing-characters/', '2', 'nvidia,audio2face,opensource',
    "NVIDIA opens sources Audio2Face — making real-time AI facial animation accessible to all game developers."],
  ['3D & VFX', 'One-to-All Animation', 'https://ssj9596.github.io/one-to-all-animation-project/', '11', 'animation',
    "One-to-All Animation: alignment-free character animation and image pose transfer from a single reference."],
  ['3D & VFX', 'PlayCanvas SOG', 'https://www.linkedin.com/posts/willeastcott_playcanvas-open-sources-sog-literally-webp-ugcPost-7374459362708180992-aHDa', '1', 'playcanvas,gaussian,opensource',
    "PlayCanvas open sources SOG — WebP for 3D Gaussian Splatting, making splat streaming efficient for the web."],
  ['3D & VFX', 'SAM 3D ComfyUI', 'https://github.com/PozzettiAndrea/ComfyUI-SAM3DObjects', '10', 'comfyui,meta,sam',
    "SAM 3D's ComfyUI custom node — segment and reconstruct 3D objects from video inside ComfyUI."],
  ['3D & VFX', 'SCAIL Animation', 'https://teal024.github.io/SCAIL/', '12', 'animation',
    "SCAIL: Studio-grade Character Animation via In-context Learning from reference motion examples."],
  ['3D & VFX', 'Slapshot Camera Track', 'https://www.tvbeurope.com/production-post/slapshot-launches-ai-camera-tracking-solution', '5', 'slapshot',
    "Slapshot launches an AI Camera Tracking solution for broadcast and production environments."],
  ['3D & VFX', 'Supercell Splat', 'https://github.com/remikaito/supercell-hack', '6', 'gaussian,opensource',
    "Supercell Splat: AI Gaussian Splatting World Generator — transform text prompts into explorable 3D worlds."],
  ['3D & VFX', 'SuperSplat 2.212', 'https://x.com/willeastcott/status/1980275626629075272', '4', 'supersplat,gaussian',
    "SuperSplat 2.212.0 release — the free and open source Gaussian Splat editor with new features."],
  ['3D & VFX', 'SuperSplat 2.16', 'https://www.linkedin.com/posts/willeastcott_supersplat-playcanvas-3dgs-ugcPost-7403794745363156992-5FM9', '11', 'supersplat,gaussian',
    "SuperSplat v2.16.0 — the free and open source Gaussian Splat Editor from PlayCanvas."],
  ['3D & VFX', 'Hunyuan WorldMirror', 'https://x.com/TencentHunyuan/status/1980930623536837013', '4', 'tencent,hunyuan',
    "Tencent open-sources Hunyuan World 1.1 (WorldMirror): a universal feed-forward 3D reconstruction model."],
  ['3D & VFX', 'Hunyuan World 1.5', 'https://x.com/TencentHunyuan/status/2001170499133653006', '12', 'tencent,hunyuan',
    "Tencent open-sources HY World 1.5, a comprehensive real-time world model framework."],
  ['3D & VFX', 'HY 3D Studio Update', 'https://x.com/TencentHunyuan/status/2012005104153678331', '15', 'tencent,hunyuan',
    "Tencent HY 3D Studio gets a significant update with new generation capabilities."],
  ['3D & VFX', 'Unreal Engine 5.7 AI', 'https://www.linkedin.com/posts/petewoodbridge_creativeai-unrealengine-ue5-ugcPost-7395478903596900352-pPxQ', '8', 'unreal',
    "Unreal Engine 5.7 gets an AI assistant to help you fix problems, generate C++ and Blueprint logic, and more."],
  ['3D & VFX', 'NVIDIA A2F Tutorial 2', 'https://www.linkedin.com/posts/nvidia-game-developer_new-tutorial-nvidia-audio2face-provides-activity-7394879709727277058-JDW5', '8', 'nvidia,audio2face',
    "New tutorial: NVIDIA Audio2Face provides real-time speech-to-facial-animation for games and interactive media."],
  ['3D & VFX', 'Wonderzoom 3D', 'https://wonderzoom.github.io/', '14', 'wonderzoom',
    "Wonderzoom: Multi-Scale 3D World Generation that lets you infinitely zoom into the details of a generated scene."],

  // ─── Audio, Music & Sound ─────────────────────────────────────────────────────
  ['Audio', 'Adobe Corrective AI Voice', 'https://www.wired.com/story/adobe-max-sneaks-2025-corrective-ai/', '6,9', 'adobe',
    "Adobe's Corrective AI can change the emotions of a voice-over — alter tone, mood, and delivery of recorded speech."],
  ['Audio', 'AIODE Music Platform', 'https://aiode.com/', '7', 'aiode',
    "AIODE: an ethically trained music creation platform — is this the future of DAWs?"],
  ['Audio', 'AIODE Ethics Article', 'https://www.techradar.com/ai-platforms-assistants/musicians-meet-your-ethical-ai-bandmates', '2', 'aiode',
    "AIODE's AI-powered music studio pays the people inspiring its virtual session players — ethical AI music."],
  ['Audio', 'AI Music Listening Stats', 'https://routenote.com/blog/morgan-stanley-report-ai-music-listening-habits/', '14', 'research',
    "Between 50–60% of listeners aged 18–44 report listening to around 2.5–3 hours of AI music per week, per Morgan Stanley."],
  ['Audio', 'ComfyUI Audio Reactive', 'https://github.com/yvann-ba/ComfyUI_Yvann-Nodes', '14', 'comfyui',
    "Super neat ComfyUI Audio Reactive node pack — drive visual generation from audio signals."],
  ['Audio', 'ComfyUI Music Tools', 'https://github.com/jeankassio/ComfyUI_MusicTools', '11', 'comfyui',
    "ComfyUI Music Tools: comprehensive music processing nodes for audio enhancement, stem separation, vocal processing, and AI denoising."],
  ['Audio', 'Fish Audio S1 TTS', 'https://fish.audio/app/text-to-speech/', '4', 'fish,tts',
    "Fish Audio S1: 'the most expressive and natural TTS model on the market', 6x cheaper than ElevenLabs."],
  ['Audio', 'GEMIDI (Gemini Music)', 'https://www.linkedin.com/posts/rikardlindstrom_personal-project-gemidi-a-music-playground-ugcPost-7378469824630509569-9ebv', '1', 'google,gemini',
    "GEMIDI: a music playground powered by Gemini, built with Google DeepMind's AI Studio by Creative Technologist Rikard Lindstrom."],
  ['Audio', 'Google TTS Improvements', 'https://blog.google/technology/developers/gemini-2-5-text-to-speech/', '11', 'google,tts',
    "Google makes improvements to its text-to-speech preview models with Gemini 2.5, improving naturalness."],
  ['Audio', 'ElevenLabs Scribe v2', 'https://www.youtube.com/watch?v=_AZ7ptRuzs8', '7', 'elevenlabs,tts',
    "ElevenLabs Scribe v2 Realtime: built for voice agents and live applications, transcribes in 150ms across 90+ languages."],
  ['Audio', 'Latent Space Audio Viz', 'https://x.com/jtydhr88/status/1996617014585049257', '11', 'stability',
    "Latent Space Explorer: free interactive audio data visualizer using UMAP and Stability's Stable Audio VAE."],
  ['Audio', 'Maya1 TTS', 'https://huggingface.co/spaces/maya-research/maya1', '7', 'tts,opensource',
    "Maya1: an amazing open-source emotional text-to-speech model with expressive, nuanced voice synthesis."],
  ['Audio', 'Minimax Song Gen', 'https://www.minimax.io/audio/music', '6', 'minimax',
    "Minimax releases a new song generator — create full songs with AI from text prompts."],
  ['Audio', 'MusicGPT Local', 'https://github.com/gabotechs/MusicGPT/', '5', 'opensource',
    "MusicGPT: application for running the latest music generation AI models locally in a performant way."],
  ['Audio', 'LANDR AI Music Study', 'https://aristake.com/ai-tools-musicians-study/', '8', 'research',
    "New Music Study by LANDR: 87% of respondents use AI tools in music. 79% for technical tasks, 66% for songwriting."],
  ['Audio', 'AI Music Listening Poll', 'https://press.dittomusic.com/only-10-of-music-makers-would-listen-to-ai-generated-music', '2', 'research',
    "Only 10% of music-makers say they would listen to AI-generated music according to a Ditto Music survey."],
  ['Audio', 'PromptSep Audio', 'https://yutongwen.github.io/PromptSep/', '10', 'promptsep',
    "PromptSep: separate any sound from a mix by describing it with a text prompt — text-guided audio source separation."],
  ['Audio', 'Qwen3-TTS', 'https://qwen.ai/blog?id=qwen3-tts-vc-voicedesign', '13', 'qwen,tts',
    "Qwen3-TTS lineup featuring VoiceDesign and VoiceClone for customisable text-to-speech synthesis."],
  ['Audio', 'Suno Studio', 'https://www.techradar.com/ai-platforms-assistants/i-tried-suno-studio-the-new-platform-that-mixes-ai-music-generation-with-hands-on-editing-like-garageband-but-smarter', '1', 'suno',
    "Suno launches Studio — calling it the 'world's first generative audio workstation', mixing AI generation with hands-on editing."],
  ['Audio', 'Young Creatives AI Music', 'https://www.youthmusic.org.uk/news/generation-ai-how-young-musicians-are-embracing-ai', '6', 'research',
    "Two thirds (63%) of young creatives say they are embracing AI to assist in their music-making creative processes."],

  // ─── Agents, Automation & Workflow ───────────────────────────────────────────
  ['Agents', 'ComfyUI Tutorials', 'https://www.youtube.com/watch?v=OyDjj7OPUzA', '2', 'comfyui',
    "A new series of short tutorials and guides to get you started with the latest technologies in ComfyUI."],
  ['Agents', 'AI Sky Replace (ComfyUI)', 'https://www.linkedin.com/posts/comfy-compositing_comfyui-aivfx-skyreplacement-ugcPost-7413397464508170241-7HD1', '13', 'comfyui',
    "AI sky replacement in 5 minutes using ComfyUI — swap any sky with a realistic AI-generated alternative."],
  ['Agents', 'ATI on Comfy Cloud', 'https://x.com/ComfyUI/status/1989107025910067469', '8', 'comfyui',
    "ATI Trajectory Control just landed on Comfy Cloud — control video object trajectories from the cloud."],
  ['Agents', 'Gemini 3 Workflow App', 'https://www.linkedin.com/posts/tianyuxu_just-vibe-coded-a-workflow-app-using-gemini-ugcPost-7396906249625243648-mvn6', '8', 'google,gemini',
    "Building a full workflow app with Gemini 3 via vibe coding — a practical example of AI-assisted development."],
  ['Agents', 'Freepik Camera Angles', 'https://x.com/freepik/status/1987945849977229466', '7', 'freepik',
    "Freepik's collaborative creation workflow including a neat camera angles node for multi-perspective generation."],
  ['Agents', 'ComfyUI Street View', 'https://github.com/ru4ls/ComfyUI_StreetView-Loader', '9', 'comfyui',
    "ComfyUI Street View URL Parser lets you 'shoot' on any street using Google Street View imagery as input."],
  ['Agents', 'ComfyUI Simple Mode', 'https://x.com/ComfyUI/status/2001387966837784880', '12', 'comfyui',
    "ComfyUI is experimenting with a Simple Mode to make complex workflows easier to share and iterate on."],
  ['Agents', 'Decart Realtime App', 'https://decart.ai/', '1', 'decart,realtime',
    "DecartAI: an open-source app and API that lets you transform your world in real time by speaking."],
  ['Agents', 'EL Cine Ad Workflow', 'https://x.com/EHuanglu/status/1989021380093046848', '8', 'comfyui',
    "EL Cine gave away this epic Ad Creation workflow for ComfyUI — full production-quality ad generation pipeline."],
  ['Agents', 'Gambo Game Agent', 'https://www.gambo.ai/', '3', 'gambo',
    "Gambo: make games with this vibe coding game agent — describe your game and watch it get built."],
  ['Agents', 'ComfyUI Feedback Sampler', 'https://github.com/pizurny/Comfyui-FeedbackSampler', '9', 'comfyui',
    "Go old school AI with this Deforum-inspired Feedback Sampler node for ComfyUI — iterative video generation."],
  ['Agents', 'Pomelli Marketing', 'https://x.com/GoogleLabs/status/1983204018567426312', '5', 'google',
    "Google launches Pomelli: a new Marketing AI Agent that analyses a brand to generate full marketing campaigns."],
  ['Agents', 'Grok Imagine (ComfyUI)', 'https://x.com/ComfyUI/status/2016748240239284287', '16', 'comfyui,xai',
    "Grok Imagine from xAI is now available in ComfyUI — use xAI's image generation inside workflows."],
  ['Agents', 'OpenEnv (Meta+HF)', 'https://www.edtechinnovationhub.com/news/meta-and-hugging-face-launch-openenv-to-advance-open-source-agentic-development', '5', 'meta,huggingface,opensource',
    "Meta and Hugging Face launch OpenEnv to advance open-source agentic development with shared environments."],
  ['Agents', 'Multi-Angle Cam Node', 'https://www.linkedin.com/posts/lorenzo-mercugliano_comfyui-aiart-generativeai-ugcPost-7392531152240193536-CSOG', '7', 'comfyui',
    "Multiple Angle Camera Control Node for ComfyUI — control camera angles across image and video generation."],
  ['Agents', 'Qwen Time Travel WF', 'https://www.linkedin.com/posts/matthew-hallett-041a3881_you-can-download-my-qwen-2511-time-travel-activity-7409670478975627264-E4zA', '13', 'comfyui,qwen',
    "Free Qwen 2511 'Time Travel' workflow for ComfyUI — transform images across different time periods."],
  ['Agents', 'IG Reels AI Agent', 'https://x.com/mikefutia/status/1982488530908479964', '5', 'agents',
    "Instagram Reels AI agent that scrapes trending Reels in your niche, analyses them with AI, and extracts creative insights."],
  ['Agents', 'NanoBanana ComfyUI Tut', 'https://www.youtube.com/watch?v=JIBba5zZ38k', '4', 'comfyui,nanobanana',
    "Tutorial: Create Consistent Characters in ComfyUI with Nano Banana for reliable character identity across generations."],

  // ─── Coding & Development ─────────────────────────────────────────────────────
  ['Coding', 'NanoBanana LoRA Code', 'https://github.com/lovisdotio/NanoBananaLoraDatasetGenerator', '11', 'nanobanana,opensource',
    "Source code for the NanoBanana Pro LoRA Dataset Generator — build training datasets for image editing models."],
  ['Coding', '360anything', 'https://360anything.github.io/', '16', '360',
    "360anything.github.io — a research project for understanding and generating 360-degree panoramic content."],
  ['Coding', 'LlamaFactory', 'https://github.com/hiyouga/LlamaFactory', '13', 'llama,opensource',
    "Easily fine-tune 100+ large language models with zero-code using Llama Factory's unified training framework."],
  ['Coding', 'Facelooker', 'https://github.com/kylan02/face_looker', '7', 'opensource',
    "Facelooker: a fun interactive headshot experience using AI face tracking — it's just cool."],
  ['Coding', 'Google Opal', 'https://blog.google/technology/google-labs/opal-expansion/', '5', 'google',
    "Google is expanding access to Opal, a no-code AI mini-app builder for creating interactive AI experiences."],
  ['Coding', 'Lovable Education', 'https://lovable.dev/classroom', '11', 'lovable',
    "Lovable is now free for teachers and students in classrooms until the end of the year — AI-assisted development for education."],

  // ─── LLMs, Chatbots & Writing ─────────────────────────────────────────────────
  ['LLMs', 'ChatGPT Relationships', 'https://www.linkedin.com/posts/tom-head-ai_46000-people-on-reddit-are-in-romantic-relationships-share-7420082425923407874-0oHz', '16', 'openai',
    "46,000 people on Reddit are reportedly in romantic relationships with ChatGPT."],
  ['LLMs', 'Anthropic Claude Apps', 'https://techcrunch.com/2026/01/26/anthropic-launches-interactive-claude-apps-including-slack-and-other-workplace-tools/', '16', 'anthropic',
    "Anthropic launches interactive Claude apps, including Slack and other workplace tools integrations."],
  ['LLMs', 'ChatGPT Images Upgrade', 'https://www.techradar.com/ai-platforms-assistants/chatgpt/chatgpt-images-just-got-a-major-upgrade-and-it-could-change-how-we-all-create', '12', 'openai',
    "ChatGPT Images just got a major upgrade that could change how we all create visual content."],
  ['LLMs', 'StreamingVLM', 'https://huggingface.co/papers/2510.09608', '3', 'huggingface',
    "StreamingVLM offers a revolutionary solution for real-time understanding of endless visual input streams."],

  // ─── Game Development & XR ───────────────────────────────────────────────────
  ['Games', 'Gaussian VRM Avatars', 'https://sites.google.com/view/gaussian-vrm', '4', 'gaussian,avatar',
    "Instant Skinned Gaussian Avatars for Web, Mobile, and VR Applications — real-time avatars everywhere."],
  ['Games', 'Japan AI Games Study', 'https://www.gamesindustry.biz/51-of-japanese-game-makers-use-generative-ai', '1', 'research',
    "New Research: 51% of Japanese Games Studios are using AI in Production."],
  ['Games', 'RosebudAI Text2Game', 'https://rosebud.ai/', '7', 'rosebud',
    "RosebudAI: a text-to-game development platform — describe a game and it builds it for you."],

  // ─── Design & Advertising ────────────────────────────────────────────────────
  ['Design', 'Freepik Spaces', 'https://www.freepik.com/spaces', '7', 'freepik',
    "Freepik launches 'Spaces': an infinite canvas for real-time collaborative AI-assisted design."],
  ['Design', 'Google Stitch', 'https://www.testingcatalog.com/google-test-new-stitch-modes-annotate-theme-interactive/', '3', 'google',
    "Google's design tool 'Stitch' tests new features including annotate, theme, and interactive modes."],
  ['Design', 'NanoBanana Photoshop', 'https://www.linkedin.com/posts/arminas-valunas-b4477255_nano-banana-plugin-for-photoshop-is-here-ugcPost-7367923639414906881-GgV7', '1', 'nanobanana,adobe',
    "Nano Banana plugin for Photoshop is here — bring Nano Banana's AI image editing directly into Photoshop."],

  // ─── Research, Learning & Other ──────────────────────────────────────────────
  ['Research', 'TikTok AI Stats', 'https://dynamoi.com/learn/statistics/tiktok-ai-content-statistics', '15', 'research',
    "TikTok AI content statistics — data on how AI-generated content is performing and spreading on the platform."],
  ['Research', 'AI Ad Spend Surges', 'https://www.billiondollarboy.com/news/ai-creator-content-ad-spend-surges-despite-growing-resistance/', '3', 'research',
    "Global Ad Spend Surges on AI Creator Content despite growing public resistance to AI-generated advertising."],
  ['Research', 'AI News Misrepresent', 'https://www.bbc.co.uk/mediacentre/2025/new-ebu-research-ai-assistants-news-content', '4', 'research',
    "Largest study of its kind (BBC & EBU) shows AI assistants misrepresent news content 45% of the time."],
  ['Research', 'AI Studio Gallery', 'https://x.com/GoogleAIStudio/status/1982121563785949255', '5', 'google,nanobanana',
    "Google AI Studio app gallery: a curated library of vibe-coded projects built with Nano Banana, Maps Grounding, and more."],
  ['Research', 'Americans Distrust AI', 'https://newsletter.smartbrief.com/sharedSummary/index.jsp?briefId=40A39351-5419-4681-94DF-31A53480B698&issueId=0C289FFD-DFF6-418F-9C6C-4DDA1DB4C0C3&copyId=8B8E9CF5-D7AA-4C1B-B89D-553A691795A2', '4', 'research',
    "Most Americans distrust AI use in media and entertainment, according to new survey data."],
  ['Research', 'NanoBanana Prompt Guide', 'https://x.com/GoogleAIStudio/status/1994480371061469306', '11', 'nanobanana,google',
    "Nano Banana Pro Ultimate Prompting Guide — comprehensive tips for getting the best results from Nano Banana."],
  ['Research', 'Envato AI Study', 'https://www.linkedin.com/posts/petewoodbridge_creativeai-report-research-activity-7396805899366899712-nlBG', '8', 'research',
    "Envato study of 1,780 creatives worldwide: AI is no longer 'emerging' — it's part of the infrastructure."],
  ['Research', 'AI Exec vs Employee', 'https://www.dayforce.com/blog/ai-buzz-into-business-value', '4', 'research',
    "New Research: 87% of executives use AI at work compared to only 27% of employees — a major adoption gap."],
  ['Research', 'Teen AI Mental Health', 'https://www.theguardian.com/technology/2025/dec/09/teenagers-ai-chatbots-mental-health-support', '11', 'research',
    "One in four 13–17 year-olds have used an AI chatbot for mental health support in the past year."],
  ['Research', 'ADHD + AI Agents', 'https://www.cnbc.com/2025/11/08/adhd-autism-dyslexia-jobs-careers-ai-agents-success.html', '7', 'research',
    "People with ADHD, autism, and dyslexia say AI agents are helping them succeed in jobs and careers."],
  ['Research', 'DM Podcast Test', 'https://open.spotify.com/episode/3AlCPd4vA9QYA1HIqBgiHx?si=CHgIo_p7TmGEKSWDEsax7A', '18', 'podcast',
    "Testing out a podcast version of the Dream Machine newsletter — audio format exploration."],
  ['Research', "Kite's Journey Short", 'https://www.youtube.com/watch?v=-Ds-Y_DF3-4', '12', 'dreamlab',
    "The Kite's Journey: Dream Lab LA's first short film brought to life using Creative AI tools."],
  ['Research', 'Google Earth + AI Tut', 'https://www.youtube.com/watch?v=JNVV4sQ_2dw', '6', 'google',
    "Tutorial: Top Uses of Google Earth with AI — combining satellite imagery with AI for creative and analytical work."],
  ['Research', 'Yale AI Adoption', 'https://www.linkedin.com/posts/neilhoyne_ai-data-research-activity-7379272781798035456-hnuV', '1', 'research',
    "Yale University published fascinating data on AI adoption that might make everyone breathe a bit easier."],
]

// Tag display names for edge labels
const TAG_LABELS = {
  google: 'Google', veo: 'Veo', flow: 'Flow', comfyui: 'ComfyUI', qwen: 'Qwen',
  wan: 'Wan', sora: 'Sora', ltx: 'LTX', runway: 'Runway', kling: 'Kling',
  heygen: 'HeyGen', higgsfield: 'Higgsfield', hedra: 'Hedra', nvidia: 'NVIDIA',
  adobe: 'Adobe', meta: 'Meta', sam: 'SAM', gaussian: 'Gaussian', decart: 'Decart',
  odyssey: 'Odyssey', openai: 'OpenAI', bfl: 'Black Forest', flux: 'FLUX',
  krea: 'Krea', tencent: 'Tencent', hunyuan: 'Hunyuan', meshy: 'Meshy',
  nanobanana: 'Nano Banana', lora: 'LoRA', relighting: 'Relighting', depth: 'Depth',
  tts: 'TTS', realtime: 'Realtime', avatar: 'Avatar', animation: 'Animation',
  supersplat: 'SuperSplat', audio2face: 'Audio2Face', elevenlabs: 'ElevenLabs',
  aiode: 'AIODE', podcast: 'Podcast', research: 'Research', opensource: 'Open Source',
  gemini: 'Gemini', worldlabs: 'World Labs', blender: 'Blender', unreal: 'Unreal',
  freepik: 'Freepik', xai: 'xAI', bytedance: 'ByteDance', anthropic: 'Anthropic',
  huggingface: 'Hugging Face', stability: 'Stability', midjourney: 'Midjourney',
  premiere: 'Premiere', aftereffects: 'After Effects',
}

const EDGE_TAGS = new Set([
  'google', 'veo', 'flow', 'comfyui', 'qwen', 'wan', 'sora', 'ltx', 'runway',
  'kling', 'heygen', 'higgsfield', 'hedra', 'nvidia', 'adobe', 'meta', 'sam',
  'gaussian', 'decart', 'odyssey', 'openai', 'bfl', 'flux', 'krea', 'tencent',
  'hunyuan', 'meshy', 'nanobanana', 'depth', 'realtime', 'avatar', 'audio2face',
  'elevenlabs', 'aiode', 'supersplat', 'gemini', 'worldlabs', 'blender', 'unreal',
  'freepik', 'xai', 'bytedance', 'lora', 'tts',
])

export function generateGraph() {
  const catPositions = {
    'Video':    { cx: 0,    cy: -800, spread: 600 },
    'Image':    { cx: 900,  cy: -400, spread: 400 },
    '3D & VFX': { cx: 900,  cy: 400,  spread: 400 },
    'Audio':    { cx: 0,    cy: 800,  spread: 300 },
    'Agents':   { cx: -900, cy: 400,  spread: 300 },
    'Coding':   { cx: -900, cy: -400, spread: 200 },
    'LLMs':     { cx: -500, cy: -700, spread: 150 },
    'Games':    { cx: 500,  cy: -700, spread: 150 },
    'Design':   { cx: -500, cy: 700,  spread: 150 },
    'Research': { cx: 500,  cy: 700,  spread: 300 },
  }

  const nodes = RAW.map(([cat, label, url, issuesStr, tagsStr, desc], i) => {
    const issues = issuesStr.split(',').map(Number)
    const tags = tagsStr.split(',')
    const pos = catPositions[cat] || { cx: 0, cy: 0, spread: 200 }

    const angle = i * 2.4
    const r = 50 + (i % 30) * 20
    const x = pos.cx + Math.cos(angle) * Math.min(r, pos.spread)
    const y = pos.cy + Math.sin(angle) * Math.min(r, pos.spread)

    return { id: `t${i}`, label, url, category: cat, issues, tags, desc: desc || '', x, y, vx: 0, vy: 0 }
  })

  const tagGroups = new Map()
  for (const node of nodes) {
    for (const tag of node.tags) {
      if (!EDGE_TAGS.has(tag)) continue
      if (!tagGroups.has(tag)) tagGroups.set(tag, [])
      tagGroups.get(tag).push(node)
    }
  }

  const edges = []
  const edgeSet = new Set()

  for (const [tag, members] of tagGroups) {
    if (members.length < 2) continue
    members.sort((a, b) => a.issues[0] - b.issues[0])
    const label = TAG_LABELS[tag] || tag

    if (members.length <= 4) {
      for (let i = 0; i < members.length; i++) {
        for (let j = i + 1; j < members.length; j++) {
          const key = `${members[i].id}-${members[j].id}`
          const keyRev = `${members[j].id}-${members[i].id}`
          if (!edgeSet.has(key) && !edgeSet.has(keyRev)) {
            edgeSet.add(key)
            edges.push({ source: members[i].id, target: members[j].id, label })
          }
        }
      }
    } else {
      for (let i = 0; i < members.length - 1; i++) {
        const key = `${members[i].id}-${members[i + 1].id}`
        const keyRev = `${members[i + 1].id}-${members[i].id}`
        if (!edgeSet.has(key) && !edgeSet.has(keyRev)) {
          edgeSet.add(key)
          edges.push({ source: members[i].id, target: members[i + 1].id, label })
        }
      }
      if (members.length > 6) {
        const mid = Math.floor(members.length / 2)
        for (const [a, b] of [[0, mid], [mid, members.length - 1]]) {
          const key = `${members[a].id}-${members[b].id}`
          const keyRev = `${members[b].id}-${members[a].id}`
          if (!edgeSet.has(key) && !edgeSet.has(keyRev)) {
            edgeSet.add(key)
            edges.push({ source: members[a].id, target: members[b].id, label })
          }
        }
      }
    }
  }

  return { nodes, edges }
}
